function E = myTotalEnergxflight(in1,in2,in3)
%MYTOTALENERGXFLIGHT
%    E = MYTOTALENERGXFLIGHT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Jul-2020 17:25:34

J = in3(:,2);
L = in3(:,4);
dphi = in2(:,4);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,7);
kt = in3(:,3);
m = in3(:,1);
phi = in1(:,4);
y = in1(:,2);
t2 = sin(phi);
t3 = L.^2;
t4 = dphi.^2;
t5 = dtheta.^2;
t6 = t2.^2;
E = J.*t4+J.*t5+dx.^2.*m+dy.^2.*m+kt.*phi.^2.*2.0+g.*m.*y.*2.0+m.*t3.*t5+m.*t3.*t4.*t6-m.*t3.*t5.*t6;
