function f_cg = myF_CoriGrav_Flight(in1,in2,in3)
%MYF_CORIGRAV_FLIGHT
%    F_CG = MYF_CORIGRAV_FLIGHT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Jul-2020 17:08:45

g = in3(:,7);
kt = in3(:,3);
m = in3(:,1);
phi = in1(:,4);
f_cg = [0.0;g.*m.*2.0;0.0;kt.*phi.*4.0];
