function f_cg = myF_CoriGrav_Flight(in1,in2,in3)
%MYF_CORIGRAV_FLIGHT
%    F_CG = MYF_CORIGRAV_FLIGHT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Jul-2020 14:52:31

g = in3(:,6);
m = in3(:,1);
f_cg = [0.0;g.*m;0.0];
