function E = myTotalEnergy_Doublestance(in1,in2,in3)
%MYTOTALENERGY_DOUBLESTANCE
%    E = MYTOTALENERGY_DOUBLESTANCE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Jul-2020 14:52:13

J = in3(:,2);
L = in3(:,9);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,12);
kf = in3(:,4);
kh = in3(:,3);
l3 = in3(:,10);
l4 = in3(:,11);
m = in3(:,1);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,5);
xh_toe = in3(:,6);
y = in1(:,2);
t2 = cos(theta);
t3 = sin(theta);
t4 = L.*t2;
t5 = L.*t3;
E = (kf.*(l4-sqrt((t4+x-xf_toe).^2+(t5+y).^2)).^2)./2.0+(J.*dtheta.^2)./2.0+(kh.*(l3-sqrt((t5-y).^2+(t4-x+xh_toe).^2)).^2)./2.0+(m.*(dx.^2+dy.^2))./2.0+g.*m.*y;
