function f_cg = myF_CoriGrav_Doublestance(in1,in2,in3)
%MYF_CORIGRAV_DOUBLESTANCE
%    F_CG = MYF_CORIGRAV_DOUBLESTANCE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 11:45:12

g = in3(:,10);
gamma_f_td = in3(:,7);
gamma_h_td = in3(:,6);
kf = in3(:,4);
kh = in3(:,3);
l = in3(:,8);
l0 = in3(:,9);
m = in3(:,1);
theta = in1(:,3);
x = in1(:,1);
x_ini = in3(:,5);
y = in1(:,2);
t2 = cos(theta);
t3 = sin(gamma_f_td);
t4 = sin(gamma_h_td);
t5 = sin(theta);
t6 = x.*2.0;
t7 = x_ini.*2.0;
t8 = y.*2.0;
t12 = -x;
t9 = l0.*t3;
t10 = l0.*t4;
t11 = l.*t5;
t13 = -t6;
t14 = t11.*2.0;
t15 = t11+y;
t16 = -t11;
t19 = t9+t12+x_ini;
t20 = t10+t12+x_ini;
t21 = (t11-y).^2;
t17 = t16+y;
t18 = t15.^2;
t22 = t19.^2;
t23 = t20.^2;
t24 = t18+t22;
t25 = t21+t23;
t26 = sqrt(t24);
t28 = sqrt(t25);
t27 = 1.0./t26;
t29 = 1.0./t28;
t30 = -t26;
t32 = -t28;
t31 = l0+t30;
t33 = l0+t32;
f_cg = [(kf.*t27.*t31.*(t7+t9.*2.0+t13))./2.0+(kh.*t29.*t33.*(t7+t10.*2.0+t13))./2.0;g.*m-(kh.*t29.*t33.*(t8-t14))./2.0-(kf.*t27.*t31.*(t8+t14))./2.0;-kf.*l.*t2.*t15.*t27.*t31-kh.*l.*t2.*t29.*t33.*(t11-y)];
