function f_cg = myF_CoriGrav_Hind(in1,in2,in3)
%MYF_CORIGRAV_HIND
%    F_CG = MYF_CORIGRAV_HIND(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 12:25:48

g = in3(:,9);
kh = in3(:,3);
l = in3(:,7);
l0 = in3(:,8);
m = in3(:,1);
theta = in1(:,3);
x = in1(:,1);
xh_toe = in3(:,5);
y = in1(:,2);
t2 = cos(theta);
t3 = sin(theta);
t6 = -x;
t4 = l.*t2;
t5 = l.*t3;
t7 = -t5;
t9 = t4+t6+xh_toe;
t10 = (t5-y).^2;
t8 = t7+y;
t11 = t9.^2;
t12 = t10+t11;
t13 = sqrt(t12);
t14 = 1.0./t13;
t15 = -t13;
t16 = l0+t15;
f_cg = [(kh.*t14.*t16.*(t4.*2.0-x.*2.0+xh_toe.*2.0))./2.0;g.*m+(kh.*t14.*t16.*(t5.*2.0-y.*2.0))./2.0;kh.*l.*t14.*t16.*(t3.*t6+t3.*xh_toe+t2.*y)];
