function f_cg = myF_CoriGrav_Fore(in1,in2,in3)
%MYF_CORIGRAV_FORE
%    F_CG = MYF_CORIGRAV_FORE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 12:25:58

g = in3(:,10);
kf = in3(:,4);
l = in3(:,8);
l0 = in3(:,9);
m = in3(:,1);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,5);
y = in1(:,2);
t2 = cos(theta);
t3 = sin(theta);
t6 = -xf_toe;
t4 = l.*t2;
t5 = l.*t3;
t7 = t5+y;
t9 = t4+t6+x;
t8 = t7.^2;
t10 = t9.^2;
t11 = t8+t10;
t12 = sqrt(t11);
t13 = 1.0./t12;
t14 = -t12;
t15 = l0+t14;
f_cg = [kf.*t13.*t15.*(t4.*2.0+x.*2.0-xf_toe.*2.0).*(-1.0./2.0);g.*m-kf.*t7.*t13.*t15;-kf.*l.*t13.*t15.*(-t3.*x+t3.*xf_toe+t2.*y)];
