function M = myMassMatrix_Flight(in1,in2)
%MYMASSMATRIX_FLIGHT
%    M = MYMASSMATRIX_FLIGHT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 12:25:38

J = in2(:,2);
L = in2(:,3);
m = in2(:,1);
M = reshape([m,0.0,0.0,0.0,m,0.0,0.0,0.0,J.*L.^2.*m],[3,3]);
