function M = myMassMatrix_Hind(in1,in2)
%MYMASSMATRIX_HIND
%    M = MYMASSMATRIX_HIND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 12:25:48

J = in2(:,2);
L = in2(:,7);
m = in2(:,1);
M = reshape([m,0.0,0.0,0.0,m,0.0,0.0,0.0,J.*L.^2.*m],[3,3]);
