function M = myMassMatrix_Flight(in1,in2)
%MYMASSMATRIX_FLIGHT
%    M = MYMASSMATRIX_FLIGHT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Jul-2020 14:52:31

J = in2(:,2);
m = in2(:,1);
M = reshape([m,0.0,0.0,0.0,m,0.0,0.0,0.0,J],[3,3]);
