function M = myMassMatrix_Hind(in1,in2)
%MYMASSMATRIX_HIND
%    M = MYMASSMATRIX_HIND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Jul-2020 15:20:02

J = in2(:,2);
m = in2(:,1);
M = reshape([m,0.0,0.0,0.0,m,0.0,0.0,0.0,J],[3,3]);
