function M = myMassMatrix_Doublestance(in1,in2)
%MYMASSMATRIX_DOUBLESTANCE
%    M = MYMASSMATRIX_DOUBLESTANCE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 12:26:06

J = in2(:,2);
L = in2(:,9);
m = in2(:,1);
M = reshape([m,0.0,0.0,0.0,m,0.0,0.0,0.0,J.*L.^2.*m],[3,3]);
