function E = myTotalEnergy_Doublestance(in1,in2,in3)
%MYTOTALENERGY_DOUBLESTANCE
%    E = MYTOTALENERGY_DOUBLESTANCE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 12:26:07

J = in3(:,2);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,11);
kf = in3(:,4);
kh = in3(:,3);
l = in3(:,9);
l0 = in3(:,10);
m = in3(:,1);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,5);
xh_toe = in3(:,6);
y = in1(:,2);
t2 = cos(theta);
t3 = sin(theta);
t4 = l.*t2;
t5 = l.*t3;
E = (kf.*(l0-sqrt((t4+x-xf_toe).^2+(t5+y).^2)).^2)./2.0+(kh.*(l0-sqrt((t5-y).^2+(t4-x+xh_toe).^2)).^2)./2.0+(m.*(dx.^2+dy.^2))./2.0+g.*m.*y+(J.*dtheta.^2.*l.^2.*m)./2.0;
