function E = myTotalEnergy_Doublestance(in1,in2,in3)
%MYTOTALENERGY_DOUBLESTANCE
%    E = MYTOTALENERGY_DOUBLESTANCE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 11:45:12

J = in3(:,2);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,10);
gamma_f_td = in3(:,7);
gamma_h_td = in3(:,6);
kf = in3(:,4);
kh = in3(:,3);
l = in3(:,8);
l0 = in3(:,9);
m = in3(:,1);
theta = in1(:,3);
x = in1(:,1);
x_ini = in3(:,5);
y = in1(:,2);
t2 = sin(theta);
t4 = -x;
t3 = l.*t2;
E = (kf.*(l0-sqrt((t4+x_ini+l0.*sin(gamma_f_td)).^2+(t3+y).^2)).^2)./2.0+(kh.*(l0-sqrt((t3-y).^2+(t4+x_ini+l0.*sin(gamma_h_td)).^2)).^2)./2.0+(m.*(dx.^2+dy.^2))./2.0+g.*m.*y+(J.*dtheta.^2.*l.^2.*m)./2.0;
