function f_cg = myF_CoriGrav_Fore(in1,in2,in3)
%MYF_CORIGRAV_FORE
%    F_CG = MYF_CORIGRAV_FORE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Jul-2020 14:10:01

D = in3(:,9);
L = in3(:,7);
g = in3(:,10);
kf = in3(:,3);
kt = in3(:,4);
l4 = in3(:,8);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,5);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = phi+theta;
t9 = -xf_toe;
t7 = cos(t6);
t8 = sin(t6);
t11 = L.*t2.*t3;
t13 = L.*t2.*t5;
t10 = D.*t7;
t12 = D.*t8;
t14 = t12+t13+y;
t16 = t9+t10+t11+x;
t15 = t14.^2;
t17 = t16.^2;
t18 = t15+t17;
t19 = sqrt(t18);
t20 = 1.0./t19;
t21 = -t19;
t22 = l4+t21;
f_cg = [kf.*t20.*t22.*(t10.*2.0+t11.*2.0+x.*2.0-xf_toe.*2.0).*(-1.0./2.0);g.*m.*2.0-kf.*t14.*t20.*t22;kf.*t20.*t22.*(t14.*(t10+t11).*2.0-t16.*(t12+t13).*2.0).*(-1.0./2.0);kt.*phi.*4.0-(kf.*t20.*t22.*(t14.*(t10-L.*t4.*t5).*2.0-t16.*(t12+L.*t3.*t4).*2.0))./2.0];
