function f_cg = myF_CoriGrav_Hind(in1,in2,in3)
%MYF_CORIGRAV_HIND
%    F_CG = MYF_CORIGRAV_HIND(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Jul-2020 14:10:07

D = in3(:,9);
L = in3(:,7);
g = in3(:,10);
kh = in3(:,3);
kt = in3(:,4);
l3 = in3(:,8);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xh_toe = in3(:,5);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = -theta;
t7 = -x;
t8 = L.*t2.*t3;
t9 = L.*t2.*t5;
t10 = phi+t6;
t11 = cos(t10);
t12 = sin(t10);
t13 = -t9;
t14 = D.*t11;
t15 = D.*t12;
t16 = t13+t15+y;
t18 = t7+t8+t14+xh_toe;
t17 = t16.^2;
t19 = t18.^2;
t20 = t17+t19;
t21 = sqrt(t20);
t22 = 1.0./t21;
t23 = -t21;
t24 = l3+t23;
f_cg = [(kh.*t22.*t24.*(t8.*2.0+t14.*2.0-x.*2.0+xh_toe.*2.0))./2.0;g.*m.*2.0-(kh.*t22.*t24.*(t9.*-2.0+t15.*2.0+y.*2.0))./2.0;(kh.*t22.*t24.*(t16.*(t8+t14).*2.0+t18.*(t9-t15).*2.0))./2.0;kt.*phi.*4.0-(kh.*t22.*t24.*(t16.*(t14+L.*t4.*t5).*2.0-t18.*(t15+L.*t3.*t4).*2.0))./2.0];
