function f_cg = myF_CoriGrav_Fore(in1,in2,in3)
%MYF_CORIGRAV_FORE
%    F_CG = MYF_CORIGRAV_FORE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Jul-2020 12:04:37

D = in3(:,9);
L = in3(:,7);
dphi = in2(:,4);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,10);
kf = in3(:,3);
kt = in3(:,4);
l4 = in3(:,8);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,5);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = phi+theta;
t7 = L.^2;
t10 = -xf_toe;
t8 = cos(t6);
t9 = sin(t6);
t12 = L.*t2.*t3;
t14 = L.*t2.*t5;
t15 = dphi.*t2.*t3;
t16 = dphi.*t2.*t5;
t17 = dtheta.*t3.*t4;
t18 = dtheta.*t4.*t5;
t20 = L.*dphi.*t3.*t4;
t22 = L.*dphi.*t4.*t5;
t11 = D.*t8;
t13 = D.*t9;
t19 = dtheta.*t12;
t21 = dtheta.*t14;
t23 = -t18;
t24 = t16+t17;
t25 = t13+t14+y;
t26 = t15+t23;
t28 = t10+t11+t12+x;
t27 = t25.^2;
t29 = t28.^2;
t30 = t27+t29;
t31 = sqrt(t30);
t32 = 1.0./t31;
t33 = -t31;
t34 = l4+t33;
f_cg = [kf.*t32.*t34.*(t11.*2.0+t12.*2.0+x.*2.0-xf_toe.*2.0).*(-1.0./2.0);g.*m.*2.0-kf.*t25.*t32.*t34;-kf.*t13.*x-kf.*t14.*x+kf.*t13.*xf_toe+kf.*t14.*xf_toe+kf.*t11.*y+kf.*t12.*y-m.*t7.*t15.*t17.*4.0-m.*t7.*t16.*t18.*4.0+kf.*l4.*t10.*t13.*t32+kf.*l4.*t10.*t14.*t32+kf.*l4.*t13.*t32.*x+kf.*l4.*t14.*t32.*x-kf.*l4.*t11.*t32.*y-kf.*l4.*t12.*t32.*y;m.*(L.*t24.*(dy-t19+t22).*2.0+L.*t26.*(dx+t20+t21).*2.0).*(-1.0./2.0)+kt.*phi.*4.0-(m.*(L.*t26.*(-dx+t20+t21).*2.0-L.*t24.*(dy+t19-t22).*2.0))./2.0+dphi.^2.*m.*t7.*sin(phi.*2.0).*2.0-(kf.*t32.*t34.*(t25.*(t11-L.*t4.*t5).*2.0-t28.*(t13+L.*t3.*t4).*2.0))./2.0];
