function M = myMassMatrixflight(in1,in2)
%MYMASSMATRIXFLIGHT
%    M = MYMASSMATRIXFLIGHT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Jul-2020 17:09:40

J = in2(:,2);
t2 = J.*2.0;
M = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,t2],[4,4]);
