function M = myMassMatrixflight(in1,in2)
%MYMASSMATRIXFLIGHT
%    M = MYMASSMATRIXFLIGHT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Jul-2020 17:25:34

J = in2(:,2);
L = in2(:,4);
m = in2(:,1);
phi = in1(:,4);
t2 = sin(phi);
t3 = J.*2.0;
t4 = L.^2;
t5 = m.*2.0;
t6 = t2.^2;
t7 = t4.*t5.*t6;
M = reshape([t5,0.0,0.0,0.0,0.0,t5,0.0,0.0,0.0,0.0,t3+t4.*t5-m.*t4.*t6.*2.0,0.0,0.0,0.0,0.0,t3+t7],[4,4]);
