function M = myMassMatrix_Fore(in1,in2)
%MYMASSMATRIX_FORE
%    M = MYMASSMATRIX_FORE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Jul-2020 14:10:01

J = in2(:,2);
t2 = J.*2.0;
M = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,t2],[4,4]);
