function E = myTotalEnergy_Doublestance(in1,in2,in3)
%MYTOTALENERGY_DOUBLESTANCE
%    E = MYTOTALENERGY_DOUBLESTANCE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Jul-2020 17:54:58

D = in3(:,17);
J = in3(:,2);
dphi = in2(:,4);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,18);
kf = in3(:,9);
kh = in3(:,8);
kt = in3(:,3);
l = in3(:,15);
l0 = in3(:,16);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,11);
xh_toe = in3(:,12);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = phi+theta;
t7 = -theta;
t8 = l.*t2.*t3;
t9 = l.*t2.*t5;
t10 = phi+t7;
t11 = dphi.*l.*t3.*t4;
t12 = dtheta.*t9;
E = m.*(-dx+t11+t12).^2+(kf.*(l0-sqrt((t9+y+D.*sin(t6)).^2+(t8+x-xf_toe+D.*cos(t6)).^2)).^2)./2.0+J.*(dphi.^2+dtheta.^2)+kt.*phi.^2.*2.0+(kh.*(l0-sqrt((-t9+y+D.*sin(t10)).^2+(t8-x+xh_toe+D.*cos(t10)).^2)).^2)./2.0+(m.*((dx+t11+t12).^2+(dy-dtheta.*t8+dphi.*l.*t4.*t5).^2))./2.0+g.*m.*y.*2.0;
