function E = myTotalEnergy_Flight(in1,in2,in3)
%MYTOTALENERGY_FLIGHT
%    E = MYTOTALENERGY_FLIGHT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Jul-2020 17:47:10

J = in3(:,2);
dphi = in2(:,4);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,10);
kt = in3(:,3);
l = in3(:,8);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = dphi.*l.*t3.*t4;
t7 = dtheta.*l.*t2.*t5;
E = m.*(-dx+t6+t7).^2+(m.*((dx+t6+t7).^2+(dy+dphi.*l.*t4.*t5-dtheta.*l.*t2.*t3).^2))./2.0+J.*(dphi.^2+dtheta.^2)+kt.*phi.^2.*2.0+g.*m.*y.*2.0;
