function E = myTotalEnergy_Hind(in1,in2,in3)
%MYTOTALENERGY_HIND
%    E = MYTOTALENERGY_HIND(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Jul-2020 12:04:45

D = in3(:,9);
J = in3(:,2);
L = in3(:,7);
dphi = in2(:,4);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,10);
kh = in3(:,3);
kt = in3(:,4);
l3 = in3(:,8);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xh_toe = in3(:,5);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = -theta;
t7 = phi+t6;
t8 = L.*dtheta.*t2.*t3;
t9 = L.*dphi.*t3.*t4;
t10 = L.*dtheta.*t2.*t5;
t11 = L.*dphi.*t4.*t5;
E = (m.*((-dx+t9+t10).^2+(dy+t8-t11).^2))./2.0+(kh.*(l3-sqrt((-x+xh_toe+D.*cos(t7)+L.*t2.*t3).^2+(y+D.*sin(t7)-L.*t2.*t5).^2)).^2)./2.0+J.*(dphi.^2+dtheta.^2)+kt.*phi.^2.*2.0+(m.*((dx+t9+t10).^2+(dy-t8+t11).^2))./2.0+g.*m.*y.*2.0;
