function E = myTotalEnergy_Hind(in1,in2,in3)
%MYTOTALENERGY_HIND
%    E = MYTOTALENERGY_HIND(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Jul-2020 14:10:07

D = in3(:,9);
J = in3(:,2);
L = in3(:,7);
dphi = in2(:,4);
dtheta = in2(:,3);
g = in3(:,10);
kh = in3(:,3);
kt = in3(:,4);
l3 = in3(:,8);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xh_toe = in3(:,5);
y = in1(:,2);
t2 = cos(phi);
t3 = -theta;
t4 = phi+t3;
E = (kh.*(l3-sqrt((-x+xh_toe+D.*cos(t4)+L.*t2.*cos(theta)).^2+(y+D.*sin(t4)-L.*t2.*sin(theta)).^2)).^2)./2.0+J.*(dphi.^2+dtheta.^2)+kt.*phi.^2.*2.0+g.*m.*y.*2.0;
