function E = myTotalEnergy_Fore(in1,in2,in3)
%MYTOTALENERGY_FORE
%    E = MYTOTALENERGY_FORE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Jul-2020 12:04:38

D = in3(:,9);
J = in3(:,2);
L = in3(:,7);
dphi = in2(:,4);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,10);
kf = in3(:,3);
kt = in3(:,4);
l4 = in3(:,8);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,5);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = phi+theta;
t7 = L.*dtheta.*t2.*t3;
t8 = L.*dphi.*t3.*t4;
t9 = L.*dtheta.*t2.*t5;
t10 = L.*dphi.*t4.*t5;
E = (m.*((-dx+t8+t9).^2+(dy+t7-t10).^2))./2.0+(kf.*(l4-sqrt((x-xf_toe+D.*cos(t6)+L.*t2.*t3).^2+(y+D.*sin(t6)+L.*t2.*t5).^2)).^2)./2.0+J.*(dphi.^2+dtheta.^2)+kt.*phi.^2.*2.0+(m.*((dx+t8+t9).^2+(dy-t7+t10).^2))./2.0+g.*m.*y.*2.0;
