function E = myTotalEnergy_Fore(in1,in2,in3)
%MYTOTALENERGY_FORE
%    E = MYTOTALENERGY_FORE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Jul-2020 17:53:12

D = in3(:,15);
J = in3(:,2);
dphi = in2(:,4);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,16);
kf = in3(:,8);
kt = in3(:,9);
l = in3(:,13);
l0 = in3(:,14);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,10);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = phi+theta;
t7 = dphi.*l.*t3.*t4;
t8 = dtheta.*l.*t2.*t5;
E = m.*(-dx+t7+t8).^2+(m.*((dx+t7+t8).^2+(dy+dphi.*l.*t4.*t5-dtheta.*l.*t2.*t3).^2))./2.0+J.*(dphi.^2+dtheta.^2)+kt.*phi.^2.*2.0+(kf.*(l0-sqrt((x-xf_toe+D.*cos(t6)+l.*t2.*t3).^2+(y+D.*sin(t6)+l.*t2.*t5).^2)).^2)./2.0+g.*m.*y.*2.0;
