function E = myTotalEnergy_Doublestance(in1,in2,in3)
%MYTOTALENERGY_DOUBLESTANCE
%    E = MYTOTALENERGY_DOUBLESTANCE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Jul-2020 12:04:27

D = in3(:,13);
J = in3(:,2);
L = in3(:,10);
dphi = in2(:,4);
dtheta = in2(:,3);
dx = in2(:,1);
dy = in2(:,2);
g = in3(:,14);
kf = in3(:,4);
kh = in3(:,3);
kt = in3(:,5);
l3 = in3(:,11);
l4 = in3(:,12);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,6);
xh_toe = in3(:,7);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = phi+theta;
t7 = -theta;
t8 = L.*t2.*t3;
t9 = L.*t2.*t5;
t10 = phi+t7;
t12 = L.*dphi.*t3.*t4;
t14 = L.*dphi.*t4.*t5;
t11 = dtheta.*t8;
t13 = dtheta.*t9;
E = (m.*((-dx+t12+t13).^2+(dy+t11-t14).^2))./2.0+(kf.*(l4-sqrt((t9+y+D.*sin(t6)).^2+(t8+x-xf_toe+D.*cos(t6)).^2)).^2)./2.0+J.*(dphi.^2+dtheta.^2)+kt.*phi.^2.*2.0+(m.*((dx+t12+t13).^2+(dy-t11+t14).^2))./2.0+(kh.*(l3-sqrt((-t9+y+D.*sin(t10)).^2+(t8-x+xh_toe+D.*cos(t10)).^2)).^2)./2.0+g.*m.*y.*2.0;
