function E = myTotalEnergy_Doublestance(in1,in2,in3)
%MYTOTALENERGY_DOUBLESTANCE
%    E = MYTOTALENERGY_DOUBLESTANCE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Jul-2020 14:09:50

D = in3(:,13);
J = in3(:,2);
L = in3(:,10);
dphi = in2(:,4);
dtheta = in2(:,3);
g = in3(:,14);
kf = in3(:,4);
kh = in3(:,3);
kt = in3(:,5);
l3 = in3(:,11);
l4 = in3(:,12);
m = in3(:,1);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,6);
xh_toe = in3(:,7);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(theta);
t5 = phi+theta;
t6 = -theta;
t7 = L.*t2.*t3;
t8 = L.*t2.*t4;
t9 = phi+t6;
E = (kf.*(l4-sqrt((t8+y+D.*sin(t5)).^2+(t7+x-xf_toe+D.*cos(t5)).^2)).^2)./2.0+J.*(dphi.^2+dtheta.^2)+kt.*phi.^2.*2.0+(kh.*(l3-sqrt((-t8+y+D.*sin(t9)).^2+(t7-x+xh_toe+D.*cos(t9)).^2)).^2)./2.0+g.*m.*y.*2.0;
