function torque_spring = torque_spring(in1,in2,in3)
%TORQUE_SPRING
%    TORQUE_SPRING = TORQUE_SPRING(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Sep-2021 16:02:14

kt = in3(:,5);
phi = in1(:,4);
torque_spring = [0.0,0.0,0.0,kt.*phi.*4.0];
