function torque_GRF_hind = torque_GRF_hind(in1,in2,in3)
%TORQUE_GRF_HIND
%    TORQUE_GRF_HIND = TORQUE_GRF_HIND(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Sep-2021 16:02:13

D = in3(:,13);
L = in3(:,10);
kh = in3(:,3);
l4 = in3(:,12);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xh_toe = in3(:,7);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = -theta;
t7 = -x;
t8 = L.*t2.*t3;
t9 = L.*t2.*t5;
t10 = phi+t6;
t11 = cos(t10);
t12 = sin(t10);
t13 = -t9;
t14 = D.*t11;
t15 = D.*t12;
t16 = t13+t15+y;
t18 = t7+t8+t14+xh_toe;
t17 = t16.^2;
t19 = t18.^2;
t20 = t17+t19;
t21 = sqrt(t20);
t22 = 1.0./t21;
t23 = -t21;
t24 = l4+t23;
torque_GRF_hind = [(kh.*t22.*t24.*(t8.*2.0+t14.*2.0-x.*2.0+xh_toe.*2.0))./2.0,kh.*t22.*t24.*(t9.*-2.0+t15.*2.0+y.*2.0).*(-1.0./2.0),(kh.*t22.*t24.*(t16.*(t8+t14).*2.0+t18.*(t9-t15).*2.0))./2.0,kh.*t22.*t24.*(t16.*(t14+L.*t4.*t5).*2.0-t18.*(t15+L.*t3.*t4).*2.0).*(-1.0./2.0)];
