function torque_GRF_fore = torque_GRF_fore(in1,in2,in3)
%TORQUE_GRF_FORE
%    TORQUE_GRF_FORE = TORQUE_GRF_FORE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Sep-2021 16:02:14

D = in3(:,13);
L = in3(:,10);
kf = in3(:,4);
l4 = in3(:,12);
phi = in1(:,4);
theta = in1(:,3);
x = in1(:,1);
xf_toe = in3(:,6);
y = in1(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = phi+theta;
t9 = -xf_toe;
t7 = cos(t6);
t8 = sin(t6);
t11 = L.*t2.*t3;
t13 = L.*t2.*t5;
t10 = D.*t7;
t12 = D.*t8;
t14 = t12+t13+y;
t16 = t9+t10+t11+x;
t15 = t14.^2;
t17 = t16.^2;
t18 = t15+t17;
t19 = sqrt(t18);
t20 = 1.0./t19;
t21 = -t19;
t22 = l4+t21;
torque_GRF_fore = [kf.*t20.*t22.*(t10.*2.0+t11.*2.0+x.*2.0-xf_toe.*2.0).*(-1.0./2.0),-kf.*t14.*t20.*t22,kf.*t20.*t22.*(t14.*(t10+t11).*2.0-t16.*(t12+t13).*2.0).*(-1.0./2.0),kf.*t20.*t22.*(t14.*(t10-L.*t4.*t5).*2.0-t16.*(t12+L.*t3.*t4).*2.0).*(-1.0./2.0)];
